CREATE DATABASE CLINICAPET;
GO

USE CLINICAPET;
GO

CREATE TABLE CLINICA(
  idClinica TINYINT PRIMARY KEY IDENTITY(1,1),
  nomeClinica VARCHAR(30) NOT NULL
);
GO

CREATE TABLE VETERINARIO(
  idVeterinario TINYINT PRIMARY KEY IDENTITY(1,1),
  idClinica TINYINT FOREIGN KEY REFERENCES CLINICA(idClinica),
  nomeVeterinario VARCHAR(20) NOT NULL
);
GO

CREATE TABLE DONO(
  idDono SMALLINT PRIMARY KEY IDENTITY(1,1),
  nomeDono VARCHAR(25) NOT NULL
);
GO

CREATE TABLE PETS(
  idPets SMALLINT PRIMARY KEY IDENTITY(1,1), 
  idDono SMALLINT FOREIGN KEY REFERENCES DONO(idDono),
  nomePet VARCHAR(20) NOT NULL
);
GO

CREATE TABLE CONSULTA(
  idConsulta SMALLINT PRIMARY KEY IDENTITY(1,1), 
  idPets SMALLINT FOREIGN KEY REFERENCES PETS(idPets),
  idVeterinario TINYINT FOREIGN KEY REFERENCES VETERINARIO(idVeterinario)
);
GO