CREATE DATABASE OPTUS_JULIA;
GO

USE OPTUS_JULIA;
GO

CREATE TABLE ARTISTA(
  idArtista SMALLINT PRIMARY KEY IDENTITY(1,1),
  nomeArtista VARCHAR(20) NOT NULL
);
GO

CREATE TABLE ESTILO(
  idEstilo TINYINT PRIMARY KEY IDENTITY(1,1),
  nomeEstilo VARCHAR(20) NOT NULL
);
GO

CREATE TABLE ALBUM(
  idAlbum SMALLINT PRIMARY KEY IDENTITY(1,1),
  idArtista SMALLINT FOREIGN KEY REFERENCES ARTISTA(idArtista),
  nomeAlbum VARCHAR(25) NOT NULL
);

ALTER TABLE ALBUM
ADD dataLanca SMALLDATETIME 

ALTER TABLE ALBUM
ADD ativo TINYINT
GO


CREATE TABLE ALBUMESTILO(
  idAlbum SMALLINT FOREIGN KEY REFERENCES ALBUM(idAlbum),
  idEstilo TINYINT FOREIGN KEY REFERENCES ESTILO(idEstilo)
);
GO

CREATE TABLE USUARIO(
  idUsuario SMALLINT PRIMARY KEY IDENTITY(1,1),
  nomeUsuario VARCHAR(25) NOT NULL,
  email VARCHAR(100) NOT NULL,
  senha VARCHAR(30) NOT NULL,
  permissao VARCHAR(30) NOT NULL
);
GO