USE EMPRESA_JULIA;
GO

SELECT * FROM CNH
SELECT * FROM EMAIL
SELECT * FROM TELEFONE
SELECT * FROM PESSOA

SELECT PESSOA.nomePessoa, TELEFONE.numeroTelefone, EMAIL.end_email, CNH.descricao FROM PESSOA
INNER JOIN TELEFONE
ON PESSOA.idPessoa = TELEFONE.idTelefone
INNER JOIN EMAIL
ON PESSOA.idPessoa = EMAIL.idEmail
INNER JOIN CNH
ON PESSOA.idPessoa = CNH.idCnh;
GO