USE LOCADORA_JULIA;
GO

SELECT * FROM EMPRESA
SELECT * FROM MARCA
SELECT * FROM CLIENTE
SELECT * FROM MODELO
SELECT * FROM VEICULO
SELECT * FROM ALUGUEL

SELECT ALUGUEL.dataRetirada, ALUGUEL.dataDevolucao, CLIENTE.nomeCliente, MODELO.nomeModelo FROM ALUGUEL
INNER JOIN CLIENTE
ON ALUGUEL.idAluguel = CLIENTE.idCliente
INNER JOIN VEICULO
ON ALUGUEL.idAluguel = VEICULO.idVeiculo
INNER JOIN MODELO
ON MODELO.idAluguel = VEICULO.idModelo;
GO